-- XML 事务演示（AppJdbcTemplate）的建库脚本，由 transaction-context.xml 的
-- <jdbc:initialize-database> 在容器刷新时执行；脚本幂等，可重复运行
CREATE SCHEMA IF NOT EXISTS innovatex;
CREATE TABLE IF NOT EXISTS innovatex.innovatex (
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(64)
);
INSERT INTO innovatex.innovatex (id, uuid)
SELECT 1, 'xml-demo-init'
WHERE NOT EXISTS (SELECT 1 FROM innovatex.innovatex WHERE id = 1);
-- 显式插入种子行(id=1)不会推进 IDENTITY 序列，重置到 2 避免后续自增插入主键冲突
ALTER TABLE innovatex.innovatex ALTER COLUMN id RESTART WITH 2;
