package com.alec.InnovateX.tv;

import lombok.Data;

import java.util.List;

@Data
public class VodInfo {
    private Integer vod_id;
    private Integer type_id;
    private Integer type_id_1;
    private Integer group_id;
    private String vod_name;
    private String vod_sub;
    private String vod_en;
    private Integer vod_status;
    private String vod_letter;
    private String vod_color;
    private String vod_tag;
    private String vod_class;
    private String vod_pic;
    private String vod_pic_thumb;
    private String vod_pic_slide;
    private String vod_pic_screenshot;
    private String vod_actor;
    private String vod_director;
    private String vod_writer;
    private String vod_behind;
    private String vod_blurb;
    private String vod_remarks;
    private String vod_pubdate;
    private Integer vod_total;
    private String vod_serial;
    private String vod_tv;
    private String vod_weekday;
    private String vod_area;
    private String vod_lang;
    private String vod_year;
    private String vod_version;
    private String vod_state;
    private String vod_author;
    private String vod_jumpurl;
    private String vod_tpl;
    private String vod_tpl_play;
    private String vod_tpl_down;
    private Integer vod_isend;
    private Integer vod_lock;
    private Integer vod_level;
    private Integer vod_copyright;
    private Integer vod_points;
    private Integer vod_points_play;
    private Integer vod_points_down;
    private Integer vod_hits;
    private Integer vod_hits_day;
    private Integer vod_hits_week;
    private Integer vod_hits_month;
    private String vod_duration;
    private Integer vod_up;
    private Integer vod_down;
    private String vod_score;
    private Integer vod_score_all;
    private Integer vod_score_num;
    private String vod_time;
    private Long vod_time_add;
    private Long vod_time_hits;
    private Long vod_time_make;
    private Integer vod_trysee;
    private Integer vod_douban_id;
    private String vod_douban_score;
    private String vod_reurl;
    private String vod_rel_vod;
    private String vod_rel_art;
    private String vod_pwd;
    private String vod_pwd_url;
    private String vod_pwd_play;
    private String vod_pwd_play_url;
    private String vod_pwd_down;
    private String vod_pwd_down_url;
    private String vod_content;
    private String vod_play_from;
    private String vod_play_server;
    private String vod_play_note;
    private String vod_play_url;
    private List<VodUrl> vod_play_url_list;
    private String vod_down_from;
    private String vod_down_server;
    private String vod_down_note;
    private String vod_down_url;
    private Integer vod_plot;
    private String vod_plot_name;
    private String vod_plot_detail;
    private String type_name;
}