-- MyBatis 主题建表脚本（H2，由 MyBatisConfig 的 EmbeddedDatabaseBuilder 执行）
CREATE TABLE IF NOT EXISTS mb_user (
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email    VARCHAR(100)
);
